### ISSUE TITLE
Uncaught TypeError: params is not iterable

### ISSUE THREAD

**Issue by YukiDayDreamer** [buschtoens/ember-lazy-mount#2]
Hi, 

I have tried to create a project by using the latest ember-cli (3.5.0), ember-engines (0.5.24) and the 0.1.0 version of this addon. It will throw this error message, and do you know how can I fix this?

Thanks

**Comment by buschtoens** [comment]
Should be easy to fix. I can take a look tomorrow.

**Comment by buschtoens** [comment]
I've just published `v0.2.0`. Can you give it a try please? 😊

**Comment by YukiDayDreamer** [comment]
Hi @buschtoens, thanks for the quick update. I have tried the same process, it works this time! I believe it works for the subroute, but if I place it in the application route, which is somehow contradictory to the original intention of this repo, it pops up this error message: `Assertion Failed: lazy-mount: Argument 'name' is missing.` I think your updates have already fulfilled my need, but it would be nice if it could be applied to the application route as well.

**Comment by buschtoens** [comment]
Which version of Ember are you using?
