### ISSUE TITLE
General maintenance, convert addon to v2 format

### ISSUE THREAD

**Issue by SergeAstapov** [buschtoens/ember-lazy-mount#611]
Thank you @buschtoens for implementing and supporting this over years!

Looks like repo need a bit of maintenance as test app needs to be updated by synchronizing with latest addon blueprint.

Additionally, this addon is great candidate for conversion to v2 format.
Although asset-loader used by this addon is not supported by Embroider and completely [swapped](https://github.com/embroider-build/embroider/blob/main/packages/compat/src/compat-adapters/ember-engines.ts), ppl using Ember CLI build pipeline still can benefit from smaller addon footprint.

@buschtoens would you like to add me as maintainer as I can help with those maintenance needs now and in future to keep this usable?

**Comment by buschtoens** [comment]
Thank you for the kind words and generous help, @SergeAstapov!

I added you as a collaborator to this repository. What's your npm username, so I can add you as an owner there as well?

**Comment by SergeAstapov** [comment]
@buschtoens thank you!

npm handle is the same as GH - SergeAstapov.
Will start with some PRs this week

**Comment by buschtoens** [comment]
@SergeAstapov Hm, that username doesn't seem to exist: https://www.npmjs.com/~SergeAstapov

**Comment by SergeAstapov** [comment]
@buschtoens ah sorry, it should be all lower case https://www.npmjs.com/~sergeastapov

**Comment by buschtoens** [comment]
@SergeAstapov great, you're invited! 😊

**Comment by SergeAstapov** [comment]
[v1.0.0](https://github.com/buschtoens/ember-lazy-mount/releases/tag/v1.0.0) was published!
