### ISSUE TITLE
onLoad and onError actions

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/ember-lazy-mount#93]
```hbs
{{lazy-mount
  this.engineName
  model=this.optionalDataForTheEngine
  onLoad=this.onLoad
  onError=this.onError
}}
```

- **`onLoad`**: _`() => void`_ — Called, when the engine was successfully loaded
- **`onError`**: _`(error: Error) => void`_ — Called, when the engine failed to load

**Comment by jfrux** [comment]
definitely need me some of this...

**Comment by buschtoens** [comment]
Shipped as [`v0.7.0`](https://github.com/buschtoens/ember-lazy-mount/releases/tag/v0.7.0). Enjoy. 🥂

**Comment by jfrux** [comment]
@buschtoens Docs say it calls it when it "starts loading".  But in general, onLoad indicates when something is fully loaded... right?

Just curious.

**Comment by jfrux** [comment]
My bad! I just saw the didLoad.

**Comment by buschtoens** [comment]
Good point though. `onLoad` conventionally means "done". I was contemplating that yesternight as well... 🤔
